version: '3.8'
services:
  eureka-server:
    ports:
      - "9999:9999"
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge
