version: '3.9'
services:
  eureka-server:
    image: mojtaba2422/ecommerce-eureka-server:latest
    container_name: ecommerce-eureka-server
    ports:
      - "9999:9999"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://ecommerce-config-server:8888
      - EUREKA_SERVER_URL=http://ecommerce-eureka-server:9999/eureka
      - EUREKA_INSTANCE_HOSTNAME=ecommerce-eureka-server
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge
    external: true
